### ISSUE TITLE
loadbalancerIP has no effect

### ISSUE THREAD

**Issue by BenGig** [haproxytech/helm-charts#103]
Maybe I am understanding this parameter completely wrong...

I have to set the listening IP of the ingress to a certain IP address. The loadbalancer used is MetalLB, the IP in question is configured to route trafic into the cluster.

In my understanding, `loadbalancerIP` sets the IP used by the ingress, but this seems wrong. The external IP used by the ingress is the IP of the node where the ingress controller was started, no matter what the parameter is set. 

So either I my interpretation of `loadbalancerIP` is wrong, or it has no effect.

**Comment by dkorunic** [comment]
@BenGig This feature is cloud provider and K8s feature, not Ingress Controller feature. In short, in case that it is physically possible to associate persistent static (and possibly public) IP to a LoadBalancer. For example on Amazon, Azure and Google Cloud, this option will cause static IP allocation to happen. In case of MetaLB, I really have no idea what happens. Sorry we can't give any more detailed support on this, as it's really not an Ingress Controller feature.
