### ISSUE TITLE
Deploy multiple kubernetes-ingress controllers

### ISSUE THREAD

**Issue by reversethread** [haproxytech/helm-charts#114]
Is it possible to deploy multiple kubernetes-ingress controllers with different ingress classes?
For example:
helm install tenant1 haproxytech/kubernetes-ingress --set controller.ingressClass=tenant1
helm install tenant2 haproxytech/kubernetes-ingress --set controller.ingressClass=tenant2

The helm chart wants to deploy an IngressClass with a name of "haproxy" each time so that will only work for the first install.

**Comment by dkorunic** [comment]
@reversethread It is possible and as you can see depending on K8s version you use, you will need to set `controller.ingressClass`: https://github.com/haproxytech/helm-charts/blob/48f59523c7c7cb51047184632ba93153c2c09f67/kubernetes-ingress/values.yaml#L143 and/or `controller. ingressClassResource.name`: https://github.com/haproxytech/helm-charts/blob/48f59523c7c7cb51047184632ba93153c2c09f67/kubernetes-ingress/values.yaml#L136

**Comment by reversethread** [comment]
Thank you. It was the ingressClassResource.name that I had overlooked.
