### ISSUE TITLE
Increased memory usage after upgrading to 1.7.x

### ISSUE THREAD

**Issue by tetsuo** [haproxytech/helm-charts#116]
I noticed a slight increase in memory usage after upgrading from `1.16.3` to `1.7.11`

A single pod always occupied 95mb when it's idle, but after the upgrade this has now stabilized at 170mb.

Tried with 1.7.0, it's the same results. Any idea what may have caused this? Thanks 👋

**Comment by dkorunic** [comment]
@tetsuo That's really expected as `1.7.x` Chart release brings `1.7` Ingress Controller (which also brought a lot of updates libraries and Go runtime `1.17`) as well as `2.4` HAProxy CE and all of these would increase the baseline requirements. If anything, we would recommend always running Ingress Controller containers with the minimum of 1GB RAM.

**Comment by tetsuo** [comment]
Thanks a lot for the explanation @dkorunic
