### ISSUE TITLE
Volume mount is overriding complete /etc/haproxy dir, configmap only has haproxy.cfg in it

### ISSUE THREAD

**Issue by dfry** [haproxytech/helm-charts#120]
The configmap that is being mounted into /etc/haproxy (/usr/local/etc/haproxy) is configured in the chart to only contain the haproxy.cfg file.  With the current chart mounting the whole volume to the /etc/haproxy path, this means that the rest of the /etc/haproxy dir is "masked" by the volume mount.  

This causes side effects when making use of other functionality that expects to write to that folder (dataplaneapi, etc) since the whole directory of /etc/haproxy becomes read-only.

If the intention is to use that configmap to just mount the config file from the config element in the values file, this volumemount should be modified to be like this:

volumeMounts:
  - name: haproxy-config
     mountPath: /usr/local/etc/haproxy/haproxy.cfg
     subPath: haproxy.cfg

https://github.com/haproxytech/helm-charts/blob/8e6fba77e04ea573da4a02bd39ea5014f42d5c63/haproxy/templates/deployment.yaml#L133

**Comment by dfry** [comment]
@dkorunic thanks for the quick merge.  When is the next scheduled release of the chart?

**Comment by yellowmegaman** [comment]
@dfry 

Hi! The problem with the subPath is that if the configMap is updated, the file won't be updated in the container.

https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
<img width="592" alt="image" src="https://github.com/user-attachments/assets/da16277e-7365-4536-b47a-7b2c616ea460">

**Comment by dkorunic** [comment]
That is absolutely correct, sadly subPath has that caveat that the contents will not be regenerated upon ConfigMap changes.
