### ISSUE TITLE
Haproxy should reload after configmap-tcp-services was updated

### ISSUE THREAD

**Issue by adamw-linadm** [haproxytech/helm-charts#134]
Hi I just stared using haproxy ass ingress controller. I want to forward multiple tcp services and everything almost behave as expected.
I use --configmap-tcp-services configuration in my controller, but haproxy don't restart after updating config map with tcp services. 
When I update config map with global configuration restart happens automatically.  It only works when I remove config map, wait around 1s and upload it again, then haproxy reloads config with current data from config map.
Is this expected behavior?
Logs:
2022/02/15 15:50:22 INFO    store/events.go:325 configmap 'ingress-controller/tcp' updated
2022/02/15 15:56:52 INFO    store/events.go:325 configmap 'ingress-controller/tcp' updated
2022/02/15 15:57:53 INFO    store/events.go:325 configmap 'ingress-controller/tcp' updated
2022/02/15 15:59:10 INFO    store/events.go:325 configmap 'ingress-controller/haproxy-kubernetes-ingress' updated
2022/02/15 15:59:13 INFO    controller.go:205 HAProxy restarted
[WARNING]  (449) : Exiting Master process...
[NOTICE]   (449) : haproxy version is 2.4.12-4b7772e
[ALERT]    (449) : Current worker #1 (452) exited with code 143 (Terminated)
[WARNING]  (449) : All workers exited. Exiting... (0)
[WARNING]  (490) : config: Can't get version of the global server state file '/var/state/haproxy/global'.
[NOTICE]   (490) : New worker #1 (493) forked
2022/02/15 15:59:48 INFO    store/events.go:325 configmap 'ingress-controller/tcp' updated
2022/02/15 16:00:05 INFO    store/events.go:325 configmap 'ingress-controller/haproxy-kubernetes-ingress' updated
2022/02/15 16:00:08 INFO    controller.go:205 HAProxy restarted
[WARNING]  (490) : Exiting Master process...
[NOTICE]   (490) : haproxy version is 2.4.12-4b7772e
[ALERT]    (490) : Current worker #1 (493) exited with code 143 (Terminated)
[WARNING]  (490) : All workers exited. Exiting... (0)
[WARNING]  (511) : config: Can't get version of the global server state file '/var/state/haproxy/global'.
[NOTICE]   (511) : New worker #1 (514) forked

Im using:
NAME   	NAMESPACE         	REVISION	UPDATED                               	STATUS  	CHART                    	APP VERSION
haproxy	ingress-controller	4       	2022-02-15 16:50:39.83672495 +0100 CET	deployed	kubernetes-ingress-1.19.0	1.7.5

**Comment by dkorunic** [comment]
@adamw-linadm For issues directly related with Ingress Controller and not with Helm Chart, please go to [Ingress Controller Issues](https://github.com/haproxytech/kubernetes-ingress/issues) and raise a corresponding issue.
