### ISSUE TITLE
Service name truncated when using controller.publishService

### ISSUE THREAD

**Issue by devblackops** [haproxytech/helm-charts#135]
Hello, I'm trying to expose the external IP of the service through the ingress object. This is done by setting `controller.publishService.enabled` to `true` in the helm chart. When enabled, the [deployment](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/controller-deployment.yaml#L98) calls a [template](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/_helpers.tpl#L108) to build the service path and passes it to `--publishService`.

The problem is this helm template [truncates](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/_helpers.tpl#L111) the service path 63 characters for some reason. Why is that? My service name was longer and I was scratching my head wondering why the service IP wasn't exposed through the ingress until I manually edited the yaml on the deployment object.

**Comment by dkorunic** [comment]
@devblackops All K8s labels *must* be 63 characters or less, but I believe this is here by mistake as there is no reason to truncate service path. Good catch.

**Comment by devblackops** [comment]
Thanks @dkorunic!
