### ISSUE TITLE
Add optional envVars to helm chart

### ISSUE THREAD

**Issue by yellowmegaman** [haproxytech/helm-charts#136]
Would love to set domain name and use it in config for acl rules

**Comment by dkorunic** [comment]
This relates to which chart, non-ingress haproxy?

**Comment by yellowmegaman** [comment]
Haproxy chart one, worked like a charm, thanks for your work!

Now the only bit is to get this variable in there

**Comment by dkorunic** [comment]
Fixed by #140. Closing.

**Comment by yellowmegaman** [comment]
@dkorunic Thank you so much for this! Awesome 🥇
