### ISSUE TITLE
Make `haproxy` chart Ingress Compatible with `kubernetes.io/tls` Secrets

### ISSUE THREAD

**Issue by austince** [haproxytech/helm-charts#139]
The current `haproxy` chart is not able to use `kubernetes.io/tls` secrets since they do not bundle the crt and key in a single file, and the chart doesn't allow mounting individual files from the `mountedSecrets` value. This effectively makes the haproxy chart incompatible with the k8s TLS ecosystem, e.g. cert-manager.

I tried to find a way to tell haproxy the exact path of the key instead of the default certPath  + `.key` but couldn't find a way. Judging from how the [k8s operator handles this case](https://github.com/haproxytech/kubernetes-ingress/blob/7859db47c26456524c7beb27dc3ba2bad90e99e2/controller/haproxy/certs/main.go#L184-L217), I'm guessing this is not supported? 

Example values:
```yaml
config: |
  frontend fe_kibana
    bind :80 ssl crt /etc/ssl/certs/tls.crt
    mode http
    option httplog
    use_backend kibana
  backend kibana
    mode http
    http-request set-header Host <kibana-host>
    http-request set-header X-Found-Cluster <id>
    server kibana <kibana-host> check maxconn 200
 
mountedSecrets:
  - volumeName: ssl-certificate
    secretName: kibana-tls
    mountPath: /etc/ssl/certs
```

What do you think about supporting the `items` projection so that there is a workaround for this case? See: https://kubernetes.io/docs/concepts/configuration/secret/#projection-of-secret-keys-to-specific-paths

**Comment by dcardellino** [comment]
@austince You can now (since cert-manager v1.7.1) use `AdditionalCertificateOutputFormats` which allows you to have a combined certificate including the privatekey. See this configuration:
```
additionalOutputFormats:
  - type: CombinedPEM
```
https://cert-manager.io/docs/usage/certificate/#additional-certificate-output-formats

Notice that you have to enable this featureGate in cert-manager itself and the webhook (extraArgs)

**Comment by austince** [comment]
@dcardellino, that's a great tip, thanks! Is this format making its way across the k8s ecosystem in terms of support?

**Comment by dcardellino** [comment]
> @dcardellino, that's a great tip, thanks! Is this format making its way across the k8s ecosystem in terms of support? 

Yes, like I wrote this is from official cert-manager doc and should be supported across the ecosystem

**Comment by dkorunic** [comment]
Closing as idle.
