### ISSUE TITLE
tcp services not added to haproxy config

### ISSUE THREAD

**Issue by ufou** [haproxytech/helm-charts#14]
Hi,

We are just trying haproxy out using this chart (latest release) on k8s 1.16.8, specifically we wish to use it for deploying a TCP service and use the load balancing least conn algorithm along side pod max conn, however even though we have added an controller.config and can see the cm created, the port does not appear in the haproxy.cfg - is this supposed to work? Or do we have to override the haproxy.cfg somehow? Maybe I missed something in the docs about this?

Please let me know if you need more info?
Thanks

**ConfigMap:**
```
apiVersion: v1
data:
  "1935": default/rtmp-broadcast:1935
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-03T16:02:22Z"
  labels:
    app.kubernetes.io/instance: rtmp
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.4.2
    helm.sh/chart: kubernetes-ingress-1.1.3
  name: rtmp-kubernetes-ingress
  namespace: default
  resourceVersion: "141774"
  selfLink: /api/v1/namespaces/default/configmaps/rtmp-kubernetes-ingress
  uid: 43b28d96-7c94-4a50-a962-de2e10dca1e0
```

**Service:**
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    haproxy.org/load-balance: leastconn
    haproxy.org/pod-maxconn: "3"
  creationTimestamp: "2020-05-03T15:28:17Z"
  labels:
    app.kubernetes.io/instance: rtmp
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.4.2
    helm.sh/chart: kubernetes-ingress-1.1.3
  name: rtmp-kubernetes-ingress
  namespace: default
  resourceVersion: "142650"
  selfLink: /api/v1/namespaces/default/services/rtmp-kubernetes-ingress
  uid: ef2be52a-03bb-40fc-b09a-c2893e03d4a5
spec:
  clusterIP: 10.109.6.30
  externalTrafficPolicy: Cluster
  loadBalancerIP: 1.2.3.4
  ports:
  - name: http
    nodePort: 30299
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31449
    port: 443
    protocol: TCP
    targetPort: https
  - name: stat
    nodePort: 30126
    port: 1024
    protocol: TCP
    targetPort: stat
  - name: rtmp-tcp
    nodePort: 30746
    port: 1935
    protocol: TCP
    targetPort: rtmp
  selector:
    app.kubernetes.io/instance: rtmp
    app.kubernetes.io/name: kubernetes-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 1.2.3.4
```

**Comment by Mo3m3n** [comment]
Hi @ufou 
If you wan to deploy TCP services you should not only expose appropriate ports in k8s service via `controller.service.tcpPorts` but first you need to provide the the confimap for tcp services via [--configmap-tcp-services](https://github.com/Mo3m3n/kubernetes-ingress/blob/master/documentation/controller.md) where controller will fetch TCP services config

**Comment by ufou** [comment]
Thanks @Mo3m3n so the `configMap` is to be created manually (eg, out of band from the helm chart)?

**Comment by ufou** [comment]
As as side note, is this expected: 
```
[WARNING] 124/141749 (30) : Can't open server state file '/var/state/haproxy/global': No such file or directory
2020/05/04 14:17:49 Running on Kubernetes version: v1.16.8 linux/amd64
E0504 14:17:49.634780       6 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 162 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1289540, 0x1e9f890)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1289540, 0x1e9f890)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/haproxytech/kubernetes-ingress/controller.ConvertIngressRules(0xc00072d680, 0x1, 0x1, 0x0)
	/src/controller/types.go:152 +0x31c
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1(0x13dbb00, 0xc0002712e0)
	/src/controller/kubernetes.go:275 +0xc8
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:195
k8s.io/client-go/tools/cache.newInformer.func1(0x129d840, 0xc0003ec5e0, 0x1, 0xc0003ec5e0)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:367 +0x1b6
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0001b64d0, 0xc000342de0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0004fb580)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005d2fb0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005d2fb0, 0x3b9aca00, 0x0, 0xc0005b0f01, 0xc00034a300)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc0004fb580, 0xc00034a300)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2fd
created by github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses
	/src/controller/kubernetes.go:334 +0x291
[NOTICE] 124/141749 (44) : New worker #1 (45) forked
```

**Comment by ufou** [comment]
So I added a configmap, it did indeed redeploy haproxy ingress - but the tcp port does still not exist in the haproxy config

**Comment by Mo3m3n** [comment]
>Thanks @Mo3m3n so the configMap is to be created manually (eg, out of band from the helm chart)?

Yes this is not currently managed by HELM 

>So I added a configmap, it did indeed redeploy haproxy ingress - but the tcp port does still not exist in the haproxy config

 Looking to the stack trace it seems that you are using an ingress rule without paths no backend, can you check that or send the ingress rules you are using

**Comment by ufou** [comment]
Yeah, I have no paths because I am only using this as a TCP load balancer, so my ingress is literally just a host definition, eg (this worked for nginx, so perhaps my assumptions that this should work with haproxy here are wrong):
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: default-rtmp-class
  creationTimestamp: "2020-05-03T12:00:46Z"
  generation: 1
  labels:
    app: default
    chart: example-default
    heritage: Tiller
    release: default
    service: default
  name: default-broadcast
  namespace: default
  resourceVersion: "129290"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/default-broadcast
  uid: 61dc0e62-e657-4756-9147-b06ca982a7f6
spec:
  rules:
  - host: rtmp.example.com
status:
  loadBalancer:
    ingress:
    - ip: 1.2.3.4
    - ip: 1.2.3.5
```

**Comment by Mo3m3n** [comment]
Yes I think we implement this differently from Nginx but if it is possible for us to have a consistent ingress config we will do.

>Yeah, I have no paths because I am only using this as a TCP load balancer

So need for that ingress rule at all, no ? it has not paths and no backends too

**Comment by ufou** [comment]
Maybe? This is probably my misunderstanding, what I'd like to do is have TCP port 1935 load balanced using the haproxy leastconn algorithm to the existing backend service we have which handles the connections from that point, I assumed an ingress would be required to allow this to happen, maybe I'm wrong?

Either way I still don't understand how one is able to alter the haproxy.cfg file of the controller to enable a TCP port/backend service?

**Comment by Mo3m3n** [comment]
>so perhaps my assumptions that this should work with haproxy 

This should at least not crash yes, even if it works in a different way. So good that his was reported 

> I assumed an ingress would be required to allow this to happen, maybe I'm wrong?

Well currently the k8s api does not handle tcp services so ingress controllers needed a workaround this. One is to use a dedicate configmap.
What you need to do with the HAProxy controller is:
- Get rid of that ingress with just a host definition (for now it is causing issues until we fix it)
- You will need to have tcp configmap like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp
  namespace: default
data:
  1935:                       # Port where the frontend is going to listen to.
    <namespace/name>:<port>   # Kuberntes service to use for this tcp service .
```
- And you need to have the k8s service of the controller exposing `1935` (via Helm as showed before)

**Comment by Mo3m3n** [comment]
So a typical helm values will look like:
```
--- 
controller:
  service:
    tcpPorts:
      - name: custom-app
        port: 1935
        targetPort: 1935
  extraArgs:
    - --configmap-tcp-services=<namespace/name>
```
And with Helm you will need to upgrade or install your app  this way:
```
helm upgrade <app-name> -f values.yml haproxytech/kubernetes-ingress
```

**Comment by ufou** [comment]
Ah, thanks, at first I made 2 changes - I tried adding a backend to the ingress (without path) and also fixed a typo I had with extraArgs I'd specified, so although the configmap was there nothing happened, once I fixed the typo, haproxy controller reloaded and then the tcp 1935 backends appeared in the haproxy.cfg file.

After that I removed the ingress completely as suggested and the backends still exist - so indeed the ingress was not required.

However I am unable to reach tcp 1935 locally via the loadbalancer svc cluster ip or loadbalancer ip.

If exec into the controller pod, I can `nc -v 127.0.0.1 1935` which works, so it's definitely listening - maybe I have misconfigured something on the svc itself, do you know if it's possible to get more verbose logging?

BTW I am still getting this error (after removing ingress):
```
[WARNING] 124/165856 (30) : Can't open server state file '/var/state/haproxy/global': No such file or directory
2020/05/04 16:58:56 Running on Kubernetes version: v1.16.8 linux/amd64
E0504 16:58:56.074437       6 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 45 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1289540, 0x1e9f890)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1289540, 0x1e9f890)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/haproxytech/kubernetes-ingress/controller.ConvertIngressRules(0xc000545100, 0x1, 0x1, 0x0)
	/src/controller/types.go:152 +0x31c
github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses.func1(0x13dbb00, 0xc0003b3450)
	/src/controller/kubernetes.go:275 +0xc8
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:195
k8s.io/client-go/tools/cache.newInformer.func1(0x129d840, 0xc0007b08c0, 0x1, 0xc0007b08c0)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:367 +0x1b6
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000406580, 0xc000352ed0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0004e3200)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000553fb0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000553fb0, 0x3b9aca00, 0x0, 0xc000483901, 0xc0003f4300)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc0004e3200, 0xc0003f4300)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2fd
created by github.com/haproxytech/kubernetes-ingress/controller.(*K8s).EventsIngresses
	/src/controller/kubernetes.go:334 +0x291
[NOTICE] 124/165856 (48) : New worker #1 (49) forked
```

**Comment by ufou** [comment]
Sorry, just found the log level directive - will try that

**Comment by Mo3m3n** [comment]
>If exec into the controller pod, I can nc -v 127.0.0.1 1935 which works, so it's definitely listening - maybe I have misconfigured something on the svc itself, do you know if it's possible to get more verbose logging?

If the haproxy/pod is listening to 1935, then this is out of the controller pod realm and probably having more logs won't help too 

>Sorry, just found the log level directive - will try that

This is about HAProxy logs, but I suspect that it won't be useful since the connection does not seem to reach the  pod/haproxy.

What you will need to do next is check the controller service and see if 1935 is exposed there.

> BTW I am still getting this error (after removing ingress):

hmm that's strange you sure you did not missed another ingress with same behavior ? anyway although it is messy but you can ignore it for now

**Comment by ufou** [comment]
yeah that is the odd thing, the controller svc does show tcp 1935 as working:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    haproxy.org/load-balance: leastconn
    haproxy.org/pod-maxconn: "3"
  creationTimestamp: "2020-05-03T15:28:17Z"
  labels:
    app.kubernetes.io/instance: default-rtmp
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.4.2
    helm.sh/chart: kubernetes-ingress-1.1.3
  name: default-rtmp-kubernetes-ingress
  namespace: default
  resourceVersion: "142650"
  selfLink: /api/v1/namespaces/default/services/default-rtmp-kubernetes-ingress
  uid: ef2be52a-03bb-40fc-b09a-c2893e03d4a5
spec:
  clusterIP: 1.2.3.4
  externalTrafficPolicy: Cluster
  loadBalancerIP: 4.4.4.4
  ports:
  - name: http
    nodePort: 30299
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31449
    port: 443
    protocol: TCP
    targetPort: https
  - name: stat
    nodePort: 30126
    port: 1024
    protocol: TCP
    targetPort: stat
  - name: rtmp-tcp
    nodePort: 30746
    port: 1935
    protocol: TCP
    targetPort: rtmp
  selector:
    app.kubernetes.io/instance: default-rtmp
    app.kubernetes.io/name: kubernetes-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 4.4.4.4
```

backend svc:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    haproxy.org/load-balance: leastconn
    haproxy.org/pod-maxconn: "3"
  creationTimestamp: "2020-05-03T16:04:34Z"
  labels:
    app: default-rtmp
    chart: mixcloud-default
    heritage: Tiller
    release: default
    service: default-rtmp-broadcast
  name: default-rtmp-broadcast
  namespace: default
  resourceVersion: "422281"
  selfLink: /api/v1/namespaces/default/services/default-rtmp-broadcast
  uid: 658e72d6-fe2d-439a-8e66-9a16a1750edb
spec:
  clusterIP: 1.2.3.4
  ports:
  - name: rtmp
    port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app: default-rtmp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by Mo3m3n** [comment]
Maybe you are trying to reach that service with the wrong IP
I see it is of type "LoadBalancer" so I expect you to reach it via an LB of public cloud.

**Comment by ufou** [comment]
We are bare-metal and using metallb for this - the ip address is correct and I can see it bound to the kube node interfaces (also this was the same ip address we were using for the nginx ingress which was previously handling the tcp 1935 service, I expect I have a typo somewhere which is causing this, i will keep digging - thanks for the input on this one, much appreciated!

**Comment by Mo3m3n** [comment]
You're welcome.
If you're stuck and need more help feel free to join our [Community Slack](https://github.com/haproxytech/kubernetes-ingress#discussion)

**Comment by ufou** [comment]
I worked out that the tcp targetPort name was wrong for the svc, so the endpoint to the deployment was not being created - after fixing that connections to the tcp port began working as expected! Thanks for the help on this one @Mo3m3n
