### ISSUE TITLE
A rollout restart, or scale down of haproxy causes 503 connection timeout errors

### ISSUE THREAD

**Issue by pnmatich** [haproxytech/helm-charts#146]
I'm using helm to run HaProxy ingress with autoscaling enabled (chart version 1.21.1). Whenever an HaProxy pod terminates (because of a scale down event, or a rollout restart), I start seeing 503 backend connection timeout errors for a few seconds.

![Screenshot from 2022-06-09 15-08-17](https://user-images.githubusercontent.com/3980722/173706333-e4e59e62-600b-40a3-92bb-9c0e24465f2f.png)

I tried adding the following example config for graceful shutdown, but that did not resolve the issue
```sh
## Example preStop for graceful shutdown
lifecycle: {}
    preStop:
      exec:
        command: ["/bin/sh", "-c", "kill -USR1 $(pidof haproxy); while killall -0 haproxy; do sleep 1; done"]
```

**Comment by dkorunic** [comment]
This `preStop` action can't possibly be right due to s6 being used and `s6-svc -1 /var/run/s6/services/haproxy` should be used instead. Note that this issue is really not related to Helm Chart, but to [Ingress Controller](https://github.com/haproxytech/kubernetes-ingress) project.

**Comment by dkorunic** [comment]
Closing the ticket due to active https://github.com/haproxytech/kubernetes-ingress/issues/464.
