### ISSUE TITLE
ERROR backend default_local_backend already exists

### ISSUE THREAD

**Issue by jobcespedes** [haproxytech/helm-charts#151]
With default backend disable, I am getting the following error:
`ERROR   global.go:194 default backend port: 31: backend default_local_backend already exists`

Chart version: `1.22.4`

**Comment by ivanmatmati** [comment]
Hi @jobcespedes , The fix is on its way. Thanks for reporting.

**Comment by dkorunic** [comment]
Issued tracked and fixed in Ingress Controller repo.
