### ISSUE TITLE
feature/add minReadySeconds as variable for haproxy charts

### ISSUE THREAD

**Issue by pupseba** [haproxytech/helm-charts#152]
There are situations where it is required to control the time between pod deletion/creation in a rolling restart. For this, using `minReadySeconds` is helpful.

This is already implemented for the [ingress controller](https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/templates/controller-daemonset.yaml#L36)

**Comment by dkorunic** [comment]
Agreed, I'll ping back once this has been completed.
