### ISSUE TITLE
mworker: fix infinite loop on master with no proxies.

### ISSUE THREAD

**Issue by RedBlackThunder** [haproxytech/helm-charts#158]
Hi guys,

the current haproxy helm chart is using the haproxy version 2.6.3, which has a bug called "mworker: fix infinite loop on master with no proxies." Because the default config map in this chart is without proxies, it will always hit this bug and just do nothing in the default setup, except eating cpu cycles.

To remediate this issue I would suggest raising the appVersion to 2.6.5. As 2.6.4 has this fix included, according to https://www.haproxy.org/download/2.6/src/CHANGELOG

Thx,
Florian

**Comment by dkorunic** [comment]
Fixed with https://github.com/haproxytech/helm-charts/commit/8a5c104f1938b1d5e3e8c835be08397493112f25.
