### ISSUE TITLE
Need `runtimeClassName` parameter support

### ISSUE THREAD

**Issue by mateuszdrab** [haproxytech/helm-charts#161]
This is a relatively new feature but I've been trying Kata containers and my plan was to move my external facing Haproxy into Kata; however, the required Helm template option is not implemented.

The pod's template needs the `spec.runtimeClassName` field

https://kubernetes.io/docs/concepts/containers/runtime-class/

**Comment by dkorunic** [comment]
I'm adding this to a feature queue, thank you @mateuszdrab.

**Comment by dkorunic** [comment]
Completed in https://github.com/haproxytech/helm-charts/commit/81fc512b3e1787d0123a4340faf4b76f5afad30e.

**Comment by mateuszdrab** [comment]
Thank you @dkorunic, once I resolve my haproxy stability issue for which I raised a separate issue I'll work on moving Haproxy to the kata containers runtime class.
