### ISSUE TITLE
ha-proxy 1.17.1 conversion yaml to json error

### ISSUE THREAD

**Issue by sankalp28** [haproxytech/helm-charts#165]
Hi,
trying to update for the ha-proxy new release v1.17.1 but i see some conversion error:

Error: YAML parse error on haproxy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
Use --debug flag to render out invalid YAML
ERROR: Resolving helm templates failed

is this being already reported and worked upon?

**Comment by dkorunic** [comment]
Hi @sankalp28 , not reported yet. Thanks, I'll check this right away.

**Comment by sankalp28** [comment]
Hi @dkorunic ,
in that case then anywhere where ha-proxy chart is the reference, 
securityContext:
  enabled: true

would always be a problem, be it values.yaml or the templated/Deployment.yaml for the apps using ha-proxy helm chart?

**Comment by dkorunic** [comment]
@sankalp28 Yes, in Helm Chart for haproxy, "securityContext.enabled" isn't supported any more, since we pass the whole `securityContext` dictionary to container security context.

**Comment by dkorunic** [comment]
Fixed in https://github.com/haproxytech/helm-charts/commit/7ac7fee3e1cea8eade0a11e0cbaa2c3e0d53453c. Sadly this was a regression on my part.
