### ISSUE TITLE
HAproxy chart doesn't render securityContext correctly

### ISSUE THREAD

**Issue by ClementGautier** [haproxytech/helm-charts#166]
Hi 👋 , I've found a bug when you try to set a `securityContext` both in Deployment and Daemonset mode:

```
$ helm template haproxy --set securityContext.enabled=true --set securityContext.runAsUser=1000 --set securityContext.runAsGroup=1000 --set kind=DaemonSet

      containers:
        - name: haproxy
          enabled: true
          runAsGroup: 1000
          runAsUser: 1000
```

PR coming soon

**Comment by dkorunic** [comment]
@ClementGautier No need for a fix, there is no need to set `securityContext.enabled` any more since we pass the whole `securityContext` as a dict for YAML rendering. Also, an issue duplicate: https://github.com/haproxytech/helm-charts/issues/165

**Comment by dkorunic** [comment]
Fixed in https://github.com/haproxytech/helm-charts/commit/7ac7fee3e1cea8eade0a11e0cbaa2c3e0d53453c. Sadly this was a regression on my part.
