### ISSUE TITLE
Add Prometheus PodMonitor for ingress-controller when deployed as Daemonset

### ISSUE THREAD

**Issue by daniel-reyzek** [haproxytech/helm-charts#169]
Currently it is not possible to get a Prometheus ServiceMonitor or PodMonitor when the ingress controller is deployed as DaemonSet.

This should be a small change. I can implement the change too :smile:

**Comment by daniel-reyzek** [comment]
I deployed the chart via ArgoCD and ServiceMonitor was created, but i couldn't get a Service even with with setting helm values `controller.Service.enabled: true`. I forgot i had an override in Argocd via helm parameter (which take precedence). Sorry and thanks!

**Comment by dkorunic** [comment]
No problem at all, I thought I am going blind :-) Thanks again for confirming (that I am not) 👍
