### ISSUE TITLE
Chart Index Not Updated, missing v1.27.1

### ISSUE THREAD

**Issue by hasanyasin** [haproxytech/helm-charts#176]
It looks like a CI run failed due to a timeout during resource allocation after the 1.27.1 release:
https://github.com/haproxytech/helm-charts/actions/runs/3961078838

Probably because of that, the latest available version listed [in the index](https://haproxytech.github.io/helm-charts/index.yaml) is still 1.27.0. That would be great if someone with necessary rights to re-run the task.

Thank you!

**Comment by dkorunic** [comment]
Thanks, looks like Github has had some sporadic issues. I've rerun jobs in question and `v1.27.1` has appeared in the index file.
