### ISSUE TITLE
Bind socket error on Kubernetes 1.25

### ISSUE THREAD

**Issue by roman-stelmakh-emesa** [haproxytech/helm-charts#178]
Haproxy Ingress Controller doesn't run on EKS 1.25 because of a bind socket error:
```
[NOTICE]   (287) : haproxy version is 2.6.6-274d1a4
[WARNING]  (287) : config : config: Can't get version of the global server state file '/var/state/haproxy/global'.
[ALERT]    (287) : Binding [/etc/haproxy/haproxy.cfg:58] for frontend http: cannot bind socket (Permission denied) for [:::80]
[ALERT]    (287) : Binding [/etc/haproxy/haproxy.cfg:82] for frontend https: cannot bind socket (Permission denied) for [:::443]
[ALERT]    (287) : Binding [/etc/haproxy/haproxy.cfg:57] for frontend http: cannot bind socket (Permission denied) for [0.0.0.0:80]
[ALERT]    (287) : Binding [/etc/haproxy/haproxy.cfg:81] for frontend https: cannot bind socket (Permission denied) for [0.0.0.0:443]
[ALERT]    (287) : [/usr/local/sbin/haproxy.main()] Some protocols failed to start their listeners! Exiting.
```
This is mostly likely because PodSecurityPolicy have been deprecated. 
The PodSecurityPolicy with **NET_BIND_SERVICE** capability doesn’t work anymore on EKS 1.25 https://github.com/haproxytech/helm-charts/blob/361fc5a200e000cad7f918218bf493eea9184296/kubernetes-ingress/templates/controller-podsecuritypolicy.yaml

**Comment by dkorunic** [comment]
@roman-stelmakh-emesa PSP issue aside, is there any special reason you are using privileged ports for listeners?

**Comment by dkorunic** [comment]
Fully resolved in https://github.com/haproxytech/helm-charts/commit/4dc71d34c3436bf027a6557994cf2d1f912a5970. However, there is no need to use privileged ports for listeners since K8s will generate service port to container port mappings anyway. Our sane defaults are as below:
```
  containerPort:
    http: 8080
    https: 8443
    stat: 1024
```

**Comment by roman-stelmakh-emesa** [comment]
@dkorunic Thank you, both solution worked well.
