### ISSUE TITLE
Make name of the includes ConfigMap in the haproxy chart include the release name (or similar) to make it possible to have more than one release/deployment in the same namespace and easier to find when there are many ConfigMaps

### ISSUE THREAD

**Issue by donothangbagsfromthehandlebar** [haproxytech/helm-charts#180]
Currently the `haproxy/templates/configmap.yaml#L35` ConfigMap have an hard coded name, `includes`, which prevents having more than deployment in the same namespace when `.includes` are used. 

By including the release name (or similar), e.g `name: {{ .Release.Name }}-{{ .Chart.Name }}-includes` , each release will have its own `includes` ConfigMap as well as making it easier to find when there are many ConfigMaps (from different charts) in the same namespace

**Comment by dkorunic** [comment]
Resolved in https://github.com/haproxytech/helm-charts/commit/1c15397d637b481a24602f082c399e44713428cd. Thanks for reporting!
