### ISSUE TITLE
need automountServiceAccountToken: false

### ISSUE THREAD

**Issue by ticteam** [haproxytech/helm-charts#192]
hello Team, 

at first, thanx for sharing this repo! 
my little change request is, to add the possibility to deploy with spec/automountServiceAccountToken 

at the haproxy/templates/deployment.yaml

thx you

**Comment by dkorunic** [comment]
Fixed in https://github.com/haproxytech/helm-charts/commit/45e304c02023cfeaee8813919a848c2bd56ad09f.
