### ISSUE TITLE
Override namespace name for kubernetes-ingress

### ISSUE THREAD

**Issue by morozovcookie** [haproxytech/helm-charts#195]
Hello , everyone! I'd like to purpose to add an option to override namespace name via parameter from `values.yaml`. 

In my case I have a one big Helm Chart and I added kubernetes-ingess as chart dependency. For now if I run `helm upgrade --install` than ingress-controller will be installed in default chart namespace, but I need to install it in different namespace. 

It is very simple change. You just need to replace `{{ .Release.Namespace }}` with `{{ default .Release.Namespace .Values.namespace.name}}` or define a template in `_helpers.tpl` which I guess the more pretties decision. 

For example, you could find this feature in [cert-manager](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/_helpers.tpl#L172)

**Comment by morozovcookie** [comment]
I found that haproxy chart already has this feature, but not in kubernetes-ingress chart.

**Comment by dkorunic** [comment]
@morozovcookie Makes sense. Changes have been already done as requested, testing/linting is in the pipeline before the actual release.

**Comment by dkorunic** [comment]
Commited in https://github.com/haproxytech/helm-charts/commit/29d68c49a2ffecbff8607a5a893efb860ea39bbf. Can you test if `namespaceOverride` value that has been added completely works for your use case?

**Comment by dkorunic** [comment]
Great, I'll close the issue for now and the release can be expected later this week if there is nothing else in the pipeline.
