### ISSUE TITLE
Helm chart configure default service which does not exist

### ISSUE THREAD

**Issue by HSoulat** [haproxytech/helm-charts#197]
Default helmchart deployment configure a default service which does not exist. Following error is displayed in pod logs : 

`2023/06/30 14:59:48 ERROR   global.go:244 default service: service 'haproxy/default-local-service' does not exist`

**Comment by dkorunic** [comment]
@HSoulat This doesn't look like Helm Chart issue, as Chart doesn't configure a default service, it relies to Ingress Controller to do so. I does, however, look like a bug in our IC and I've passed this on to our IC developer team.

**Comment by dkorunic** [comment]
Issue has been identified in the IC and fix is in the queue. Again, it's not related to Helm Chart, but with the race condition of K8s events process and the artificial injection of K8s events in IC.
