### ISSUE TITLE
Linking controller.ingressClassResource.name ⋄ controller.ingressClass

### ISSUE THREAD

**Issue by Frankkkkk** [haproxytech/helm-charts#199]
Hi,

Is there any reason that the `controller.ingressClassResource.name` and `controller.ingressClass` parameters are not linked together ?

The use case is setting up two ingress controllers on the same cluster. We'd need to setup these two coupled parameters.

I'd be interesting to define one if the other is defined, but maybe there's a reason for it. For example:
```yaml
    controller:
      ingressClass: my-haproxy
```
would automatically setup the ingressClassResource to the same name (or vice-versa).

Thanks and cheers !

**Comment by dkorunic** [comment]
Hi @Frankkkkk, more information how those parameters are used can be found [here](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/ingressclass.md). In short, `ingress.class` is a legacy way of designating a Controller and there is no reason to link with `ingressClassResource.name`.
