### ISSUE TITLE
API v1alpha1 deprecated but no newer version available

### ISSUE THREAD

**Issue by PKizzle** [haproxytech/helm-charts#200]
This issue has been moved over from [the kubernetes-ingress repo](https://github.com/haproxytech/kubernetes-ingress/issues/554).

When starting kubernetes-ingress I receive the error message:
Global CR defined in API core.haproxy.org/v1alpha1 is DEPRECATED, please upgrade

However, the latest version of the official helm chart still ships with API version v1alpha1.

**Comment by dkorunic** [comment]
Resolved in https://github.com/haproxytech/helm-charts/commit/a69d401ee361a5956844cd76abb2f30979cb9326. Thanks for reporting!

**Comment by dkorunic** [comment]
@PKizzle Have in mind however that Helm itself will [never upgrade CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/), keeping them up to date is a manual task.
