### ISSUE TITLE
Release 1.32.3 of kubernetes-ingress helm chart appears not available

### ISSUE THREAD

**Issue by allenporter** [haproxytech/helm-charts#204]
The latest version of the kubernetes-ingress chart at https://haproxytech.github.io/helm-charts/index.yaml appears to be `1.32.2` so the latest tagged version of the chart `1.32.3` [ref](https://github.com/haproxytech/helm-charts/commit/4a4f27ff07b7e429be2e6285a9dedea48579e9b5) does not appear to be available.  This may be user error as i'm not familiar with the chart index files in detail, but i'm assuming its right given its not working in an automated release process i'm using (renovate + flux).

**Comment by allenporter** [comment]
This appears fixed with 1.32.4

**Comment by dkorunic** [comment]
Thank you @allenporter and sorry for not responding earlier. I've pushed a new release upon your ticket and as you've already noticed, pipeline has succeeded and a new release has been uploaded.
