### ISSUE TITLE
option to set security context for deployment in helm-chart

### ISSUE THREAD

**Issue by krishau99** [haproxytech/helm-charts#210]
I want to run the kubernetes-ingress in PSA restricted mode, and as far as I can see there is nothing preventing this, except "allowPrivilegeEscalation" is set to true by default in the deployment.

I can't find any way to set this in the current chart, is it possible to add functionality so that the security context for the pods can be defined as a value in the helm chart?

**Comment by dkorunic** [comment]
@krishau99 NET_BIND_SERVICE does not apply if allowPrivilegeEscalation. While we have previously had allowPrivilegeEscalation as a tunable, it has also caused users to frequently disable it and have HAProxy service bind failures on privileged ports that were previously used.

**Comment by krishau99** [comment]
We tested deploying the helm-chart, and then manually set "allowPriviledgeEscalation" to false after the helm install, and as far as I can see, NET_BIND_SERVICE is not directly related to "allowPriviledgeEscalation"?

The documentation on the PSA-standards also states that the NET_BIND_SERVICE is allowed in the restricted mode, where "allowPriviledgeEscalation" must be set to false. Since this is the case, I can't see how these to are correlated. https://kubernetes.io/docs/concepts/security/pod-security-standards/

Either way, setting "allowPriviledgeEscalation" to false worked when we tested it, and we got to run the ingress-controller in restricted mode. 

The following manifest is how we deploy the helmrelease. 

`---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxytech
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.33.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: fsp-helm
        namespace: flux-system
  targetNamespace: haproxytech
  install:
    createNamespace: true
    remediation:
      retries: 4
  values:
    fullnameOverride: kubernetes-ingress
    controller:
      logging:
        level: debug
      image:
        repository: <registry>/haproxy/kubernetes-ingress
        tag: '1.10.8'
        pullPolicy: IfNotPresent
      service:
        type: LoadBalancer
        enablePorts:
          http: false
          stat: false
      ingressClassResource:
        default: true
      ingressClass: null
    defaultBackend:
      enabled: false`

**Comment by dkorunic** [comment]
That's fine. I can ensure you that NET_BIND_SERVICE does not work when allowPriviledgeEscalation is set to false, so customers binding to privileged ports would have their IC stop working and that's why we don't set allowPriviledgeEscalation to false by default.

**Comment by Heltev** [comment]
According to the official Kubernetes documentation on PSA, https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted, a pod needs

- allowPrivilegeEscalation: false
- capabilities.drop: ALL
- capabilities.add: NET_BIND_SERVICE (optional)

in order to run under the restricted policy. How can that be the case if NET_BIND_SERVICE does not work with allowPrivilegeEscalation: false?

**Comment by dkorunic** [comment]
It doesn't really work, whatever K8s documentation says. I've done a double check and with the following (as discussed) configuration:
```
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
```
And with containerPort configuration as below:
```
  containerPort:
    http: 80
    https: 443
    stat: 1024
```

We would expect that NET_BIND_SERVICE capability will activate and permit binding to privileged ports, but due to bugs involved with how K8s resolves ambient capabilities, that doesn't happen:

```
$ kubectl logs haproxy.kubernetes-ingress-98d8944ff-ld4nc | grep bind
[ALERT]    (284) : Binding [/etc/haproxy/haproxy.cfg:48] for frontend http: cannot bind socket (Permission denied) for [:::80]
[ALERT]    (284) : Binding [/etc/haproxy/haproxy.cfg:61] for frontend https: cannot bind socket (Permission denied) for [:::443]
[ALERT]    (284) : Binding [/etc/haproxy/haproxy.cfg:47] for frontend http: cannot bind socket (Permission denied) for [0.0.0.0:80]
[ALERT]    (284) : Binding [/etc/haproxy/haproxy.cfg:60] for frontend https: cannot bind socket (Permission denied) for [0.0.0.0:443]
```

I hope this clears the matters. We can, of course, expose `allowPrivilegeEscalation` to customers, but that can end up with Ingress Controller deployment being broken.

**Comment by dkorunic** [comment]
Added support for this in https://github.com/haproxytech/helm-charts/commit/5404ee69a4fe27ab8ab37992f9eb46b0d0ae4b92, as well as documentation referring to issues w/ NET_BIND_SERVICE and a default of allowPrivilegeEscalation false.
