### ISSUE TITLE
Helm upgrade failed due to Job resource

### ISSUE THREAD

**Issue by mateuszdrab** [haproxytech/helm-charts#215]
Hello

It seems that the chart version 1.35.* creates a Job resource called `crdjob` which inherits the `initContainers` from `.Values.controller.initContainers`.

In my case, this results in an upgrade failure because my init container installs crowdsec's plugin into my instance and requires extra volumes (from `.Values.controller.extraVolumes`) which are not defined in this job.

If init containers are needed in the job resource, can they be moved to their own values reference?

Thanks

**Comment by dkorunic** [comment]
Thanks @mateuszdrab, we can safely remove initContainers from CRD job and I'll happily do that right now.

**Comment by mateuszdrab** [comment]
Thank you @dkorunic
