### ISSUE TITLE
External IP is never assigned to LoadBalancer service for 1.38.0

### ISSUE THREAD

**Issue by monrax** [haproxytech/helm-charts#227]
Hi, I use the `kubernetes-ingress` chart as a dependency and I was just trying out the latest release 1.38.0 when I noticed the external IP got stuck at `<pending>` for longer than usual. I inspected the service and turns out the `.spec.loadBalancerClass` field is set to the literal string `"nil"` (which can't be changed once it has been set):

```yaml
apiVersion: v1
kind: Service
metadata:
  # ...
spec:
  # ...
  loadBalancerClass: nil 
  ports:
     # ...
status:
  loadBalancer: {}
```

Looking at the recent commits it seems the issue has to do with [setting the default value to nil](https://github.com/haproxytech/helm-charts/commit/4254655257cb9c6069fc8d50f37d13fc36707871#diff-3824aec2faa0ade22075391132297de8b0ee57b8d89c097ead844020022e23baR439), when perhaps it should be [null](https://yaml.org/type/null.html).

I tried both setting it to null and leaving it empty and this worked for microk8s with metallb, but not for remote EKS and GKE clusters. According to the [documentation](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class):

> If you specify .spec.loadBalancerClass, it is assumed that a load balancer implementation that matches the specified class is watching for Services. Any default load balancer implementation (for example, the one provided by the cloud provider) will ignore Services that have this field set. 

Not sure if setting the `.spec.loadBalancerClass` value to `null` counts as "specifying" it as well.

**Comment by dkorunic** [comment]
Thank you @monrax , this is sadly a bug that went in https://github.com/haproxytech/helm-charts/commit/4254655257cb9c6069fc8d50f37d13fc36707871 and I haven't noticed `nil` during review :-( Build `1.38.1` with a fix is in the pipeline.
