### ISSUE TITLE
Probes port 1042 typo?

### ISSUE THREAD

**Issue by nosmicek** [haproxytech/helm-charts#242]
When we deployed haproxy-ingress controller via helm charts we noticed one small thing.

We do get Startup probe down all the time. I think that the problem might come from small typo in deployments.

From what i can tell the kubernetes-ingress opens by default port 10**24** (https://github.com/haproxytech/kubernetes-ingress/blob/c7a6f730028a9299481c2a0ac6402e6d74c199a0/pkg/utils/flags.go#L89) for stats, there is no port 1042 mentioned in whole repo (except some irrelevant files). So unless overriden by --stats-bind-port, the stats port is IMHO opened on 1024.

But this helm chart deploys all the probes by default on port 1042.

We internally have to reconfigure probes to use stats at port 1024 and everything works as expected.

**Comment by dkorunic** [comment]
No, healthz bind port is **tcp/1042** by default:
https://github.com/haproxytech/kubernetes-ingress/blob/c7a6f730028a9299481c2a0ac6402e6d74c199a0/pkg/utils/flags.go#L97
