### ISSUE TITLE
preStop hook fails (in log)

### ISSUE THREAD

**Issue by theoriginalgri** [haproxytech/helm-charts#245]
I've uncommented the default `preStop` command introduced within https://github.com/haproxytech/helm-charts/pull/41. When deleting a running pod, this always posts `FailedPreStopHook` events:

```
➜  ~ kubectl get events -n haproxy | grep FailedPreStopHook
10m         Warning   FailedPreStopHook        pod/db-haproxy-555788f68f-chl5q    PreStopHook failed
11m         Warning   FailedPreStopHook        pod/db-haproxy-555788f68f-ht7c8    PreStopHook failed
12m         Warning   FailedPreStopHook        pod/db-haproxy-555788f68f-mmkz8    PreStopHook failed
9m39s       Warning   FailedPreStopHook        pod/db-haproxy-555788f68f-vjxwx    PreStopHook failed
9m55s       Warning   FailedPreStopHook        pod/db-haproxy-555788f68f-vx7wg    PreStopHook failed
9m54s       Warning   FailedPreStopHook        pod/db-haproxy-555788f68f-xt82x    PreStopHook failed
```

While this might gracefully shutdown haproxy, kubernetes will still route traffic to the pod while it shuts down. In addition, `FailedPreStopHook` is posted to the events: My guess is that's because the script is being interrupted when the main entrypoint shuts down.

When replacing the `preStop` command with a simple `command: ["/bin/sh", "-c", "sleep 30"]`, kubernetes is able to stop traffic flowing to the endpoint.

Since I don't know how to fix the `FailedPreStopHook` but still want to ensure no traffic is routed before termination, I changed the command to:

```
command: ["/bin/sh", "-c", "sleep 20; kill -USR1 $(pidof haproxy); while killall -0 haproxy; do sleep 1; done"]
```

**Comment by dkorunic** [comment]
We use S6 for multi-process management inside a container and kind of script mentioned above doesn't really do anything, it just causes HAProxy process to start up and up and up again in the loop.

**Comment by theoriginalgri** [comment]
Sorry for the confusion, I was linking to the wrong PR and should have linked https://github.com/haproxytech/helm-charts/pull/102 instead and explicitly state I am speaking of haproxy itself, not the ingress controller.
