### ISSUE TITLE
Not able to set custom error pages on the response of 404 and 503 ! Tried Configmaps and Values.yaml ! 

### ISSUE THREAD

**Issue by abhi-gaur** [haproxytech/helm-charts#249]
#-------Configmaps----------#

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-pages
  namespace: haproxy-controller
data:
  404.html: |
    <!DOCTYPE html>
    <html>
      <head><title>404 Not Found</title></head>
      <body>nhi pta kaha h</body>
    </html>
  503.html: |
    <!DOCTYPE html>
    <html>
      <head><title>503 Service Unavailable</title></head>
      <body>Custom 503 Service Unavailable page</body>
    </html>

#----------Values.yaml -------------#

controller:
  ingressClassResource:
    enabled: true
  stats:
    enabled: true
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
    metrics:
      relabelings:
      - replacement: cl1
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: hostname
    ctrlMetrics:
      relabelings:
      - replacement: cl1
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: hostname
  extraVolumes:
    - name: haproxy-errors
      configMap:
        name: haproxy-errors
  extraVolumeMounts:
    - name: haproxy-errors
      mountPath: /etc/haproxy/errors
  configSnippet: |
    http-errors haproxy-errors
      errorfile 404 /etc/haproxy/errors/404.http

    frontend http
      bind :80
      default_backend webservers
      errorfiles haproxy-errors
      http-response return status 404 default-errorfiles if { status 404 }

    backend webservers
      balance roundrobin
      server web1 127.0.0.1:8080 check

#--------second values.yaml --------#

controller:
  ingressClassResource:
    enabled: true
  stats:
    enabled: true
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
    metrics:
      relabelings:
      - replacement: cl1
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: hostname
    ctrlMetrics:
      relabelings:
      - replacement: cl1
        targetLabel: cluster
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: hostname
  extraVolumes:
    - name: haproxy-errors
      configMap:
        name: haproxy-errors
  extraVolumeMounts:
    - name: haproxy-errors
      mountPath: /etc/haproxy/errors

**Comment by dkorunic** [comment]
Hi @abhi-gaur, here are the steps to make it work:

1. create a ConfigMap object containing errorfile (for instance `haproxy-controller/errorfile`), as documented [here](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--configmap-errorfiles).

1. add `--configmap-errorfiles=haproxy-controller/errorfile` parameter referencing errorfile and its namespace to [extraArgs](https://github.com/haproxytech/helm-charts/blob/4d0cffca3b880ee0d8bb4b26f4c5644dd26f66a2/kubernetes-ingress/values.yaml#L321) in your Helm Chart values override.

**Comment by dkorunic** [comment]
Also note, it's not `data: 404.html: ...`, it is `data: 404: ...`, where number maps to HTTP Status Code.
