### ISSUE TITLE
ServiceMonitor is not creating

### ISSUE THREAD

**Issue by nauqru** [haproxytech/helm-charts#251]
The ServiceMonitor is not created from the chart when the flag in values serviceMonitor.enabled is set to true.
This is probably due to an additional condition in the chart https://github.com/haproxytech/helm-charts/blob/main/haproxy/templates/servicemonitor.yaml#L17

**Comment by dkorunic** [comment]
Condition is correct, but if you are using ArgoCD or some alternative, Capabilities.APIVersions are not fully populated when exposed to Helm.

**Comment by YumeNoTenshi** [comment]
seems this is the issue with helm 4
