### ISSUE TITLE
How to allow HA proxy to use the privilege port for peers configuration ?

### ISSUE THREAD

**Issue by Govind10g** [haproxytech/helm-charts#263]
Hi Team,

I m got below response from the HA proxy community, Need some help to enable the flag as getting below error -

/ # haproxy -db -f /etc/haproxy/haproxy.cfg -L node-1
[NOTICE]   (25) : haproxy version is 2.9.6-9eafce5
[ALERT]    (25) : Binding [/etc/haproxy/haproxy.cfg:20] for peers section node-1: cannot bind socket (Address not available) for [172.20.248.61:80]

Suggestion from HA proxy community, so how we will do the same in K8s deployment ? 
![image](https://github.com/user-attachments/assets/d31434e6-676f-491d-87c8-a3e34bcb2104)

**Comment by Govind10g** [comment]
Hi Sir @dkorunic  - Do you know about this suggestion ? 
How we can do the same through helm charts. 

I m very new in HA proxy, need some expert guidance to help me on this issue.

**Comment by Govind10g** [comment]
Hi @dkorunic  -

I tried to bind directly the pod ip of HA proxy by using K8s headless service but still not able to break this issue.

```
/ # haproxy -db -f /etc/haproxy/haproxy.cfg -L node-2
[NOTICE]   (58) : haproxy version is 2.9.6-9eafce5
[ALERT]    (58) : Binding [/etc/haproxy/haproxy.cfg:21] for peers section node-2: cannot bind socket (Address not available) for [10.34.76.23:1024]
[ALERT]    (58) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.
```

Can you provide me some guidance on this issue ?

**Comment by Govind10g** [comment]
Hi @dkorunic -

Would be great if you provide me some hint on this issue ? your assistance would be greatly appreciated.

As I m able to resolve to direct POD IP but still getting the Address not available issue.

**Comment by dkorunic** [comment]
Closing as resolved (through community chat).
