### ISSUE TITLE
[kubernetes-ingress]  configure custom defaultBackend 

### ISSUE THREAD

**Issue by fauverick** [haproxytech/helm-charts#268]
I just upgraded to ingress controller v3.0 and I noticed that all defaultBackend configs have been deleted from the kubernetes-ingress helm chart for app version 1.8+. When no ingress rules match, the ingress controller displays a default Not Found web page. If I don't want to use this default page, how can I configure this?

**Comment by dkorunic** [comment]
We have removed default backend sidecar quite a while ago and our Ingress Controller is handling default backend directly. In case you would like to configure this further, you can change [default-backend-service](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--default-backend-service) and [default-backend-port](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--default-backend-port) by adding them to startup arguments (`controller.extraArgs`).

**Comment by fauverick** [comment]
Thank you!
