### ISSUE TITLE
kubernetes-ingress: Add PodMonitor as alternative to ServiceMonitor

### ISSUE THREAD

**Issue by phihos** [haproxytech/helm-charts#270]
Hi,

every time when the HPA adds or removes a replica or when a new deployment is rolled out I get a minor shock because the request graph looks like this:
![image](https://github.com/user-attachments/assets/22c70a52-4c03-4213-a4b7-2b6997cf54e5)
The graph above should actually be a straight line slightly tilted downward.

This happens because while the pods are already in terminating state they continue to return responses for the requests in flight. At that time the service does not contain the pod anymore though and request metrics get "lost". To mitigate that [PodMonitors](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#podmonitor) could be used instead.

I can implement this for you if it would be accepted as feature of the `kubernetes-ingress` helm chart.

**Comment by dkorunic** [comment]
Hi @phihos , we are open to all contributions. There is already support for ServiceMonitors, so I think adding PodMonitors should be fairly trivial. Thanks!

**Comment by dkorunic** [comment]
Resolved w/ https://github.com/haproxytech/helm-charts/commit/efe146b6314ce22d73ca665c2badfe0ca4c6a3a4. Thanks!
