### ISSUE TITLE
Missing support priorityClassName and HPA

### ISSUE THREAD

**Issue by claudod** [haproxytech/helm-charts#29]
Hi, I'm using HAProxy helm chart and there are mainly 2 important features which I believe are missing :
- Support for HPA (when using deployment controller)
- Support for priorityClassName
Are you planning to add these features ?

**Comment by dkorunic** [comment]
We plan to add both, but `priorityClassName` will most likely happen sooner due to trivial changes required. Thanks for reporting!

**Comment by dkorunic** [comment]
Development of HPA support is in progress.

**Comment by slawekww** [comment]
@dkorunic I'm interested with HPA support. If you need support, I could contribute to HPA via pull request.

**Comment by dkorunic** [comment]
@slawekww It's on the way, most likely the next thing after fixing some of the observed bugs.

**Comment by dkorunic** [comment]
@slawekww Resolved in [1.9.0 release](https://github.com/haproxytech/helm-charts/releases/tag/kubernetes-ingress-1.9.0). Thanks!
