### ISSUE TITLE
Support extraContainers / extraVolumes - for sidecars

### ISSUE THREAD

**Issue by EFX-PXT1** [haproxytech/helm-charts#35]
Be great if the chart had support for extraContainers which might be added as sidecars.
Personal example being deployment of fluent-bit to accept and parse syslog messages.
Generally useful to support.

**Comment by dkorunic** [comment]
Agreed, we have previously been asked for some other sidecars as well.

**Comment by dkorunic** [comment]
Fixed by #39. Thanks @EFX-PXT1, closing the issue.
