### ISSUE TITLE
[kubernetes-ingress] Unable to start with unprivileged config

### ISSUE THREAD

**Issue by tbnguyen1407** [haproxytech/helm-charts#49]
**Problem**

Pod cannot start when setting unprivileged flag in values file

```
2020/12/21 08:25:18 HAProxy Ingress Controller v1.4.10 6f9c630

2020/12/21 08:25:18 Build from: git@github.com:haproxytech/kubernetes-ingress.git
2020/12/21 08:25:18 Build date: 2020-11-20T10:33:03

2020/12/21 08:25:18 ConfigMap: default/haproxy-kubernetes-ingress
2020/12/21 08:25:18 Ingress class:
2020/12/21 08:25:18 Publish service:
2020/12/21 08:25:18 Default backend service: default/haproxy-kubernetes-ingress-default-backend
2020/12/21 08:25:18 Default ssl certificate: default/haproxy-kubernetes-ingress-default-cert
2020/12/21 08:25:18 Controller sync period: 5s
2020/12/21 08:25:18 PANIC   controller.go:241 mkdir /etc/haproxy/certs: permission denied
```

**Reproduce**

`helm install haproxy haproxytech/kubernetes-ingress --set controller.unprivileged=true`

**Comment by dkorunic** [comment]
This feature was intended for upcoming 1.5 Ingress Controller image. We'll internally discuss if we'll backport required features to 1.4 branch or wait for 1.5 final release and I'll get back to you.

**Comment by tbnguyen1407** [comment]
Thanks for the info. I also notice a privileged initContainer is created when enabling this config. It would be nice to make it optional for hardened environment.

**Comment by dkorunic** [comment]
@tbnguyen1407 As much as we would like, it's unavoidable as otherwise Controller can't bind privileged ports. Making it optional would most likely cause people to stumble on privileged ports issue when running unprivileged and we in reality use initContainer just to run a single sysctl.

**Comment by tbnguyen1407** [comment]
What about binding to unprivileged ports on container by default, while maintaining default ports for Service

* containerPort: 8080/8443
* servicePort: 80/443

I checked some other controllers are using this approach (Kong, Traefik)

**Comment by Mo3m3n** [comment]
That would probably work @tbnguyen1407 except when using hostNetwork/hostPort configuration where in such case the service layer is usually not used to translate 8080 --> 80 and the connection is made directly to the k8s node.
Although this use case is not a k8s best practice, but still users in such case, and without initContainer, won't be able to run unprivileged mode and keep listening on 80/443. 

We have considered other alternatives but they all seem to have their limitations.
Example:
- Using linux capabilities, issue is https://github.com/kubernetes/kubernetes/issues/56374
- Setcap on docker images itself, issue is image won't work with old kernels with Aufs

Anyway users feedback is welcome to have the right compromise.
