### ISSUE TITLE
Disable defaultBackend?

### ISSUE THREAD

**Issue by mbwhelan** [haproxytech/helm-charts#50]
Is there a way to disable creating the defaultBackend templates?  I have another ingress controller providing the default backend and would like to avoid the creation of extra objects and resources.

**Comment by dkorunic** [comment]
@mbwhelan At this moment no, but I'll add this as a feature request.

**Comment by Mo3m3n** [comment]
@mbwhelan  Does this PR https://github.com/haproxytech/helm-charts/pull/52/files answers your question ?

**Comment by dkorunic** [comment]
Closing due to merged #52 and new release **1.11.0** of HAProxy Ingress Controller.

**Comment by mbwhelan** [comment]
Thanks!
