### ISSUE TITLE
Cannot install haproxy with "admin" role in namespace

### ISSUE THREAD

**Issue by regentov** [haproxytech/helm-charts#63]
I am not a cluster admin. But have admin rights in a namespace.
Trying to install haproxy 1.1.4 chart.
Got a helm error like
`Unable to continue with install: could not get information about the resource: podsecuritypolicies.policy "my-haproxy" is forbidden: User "myname" cannot get resource "podsecuritypolicies" in API group "policy" at the cluster scope
`

https://kubernetes.io/docs/concepts/policy/pod-security-policy/ claims that a PodSecurityPolicy is a cluster-wide resource so I am unable to install this chart not being a cluster admin.

I should be able to turn off use of PodSecurityPolicy resource.

**Comment by regentov** [comment]
#62

**Comment by dkorunic** [comment]
Right, that's the unfortunate consequence -- in any case fix has been merged and I'll close this.
