### ISSUE TITLE
pod-maxconn doesn't work

### ISSUE THREAD

**Issue by guanzo** [haproxytech/helm-charts#65]
Chart version: `1.12.3`

I'm pretty sure my config is correct. I can see the annotation on the service.

```yml
# helm values

controller:
  service:
    type: LoadBalancer
    annotations:
      haproxy.org/pod-maxconn: 5 # testing low number
```

My understanding is that with the above config, no pod will receive more than 5 concurrent connections. Any more connections will be queued up until there's an open slot. However as I test it, I can make hundreds of concurrent connections to each pod.

**Comment by dkorunic** [comment]
@guanzo `haproxy.org/pod-maxconn` annotation is a Service annotation and not an Ingress annotation (which you've attempted to do in the example above), as per [documentation](https://www.haproxy.com/documentation/kubernetes/latest/configuration/service/#pod-maxconn), the example is also in the linked documentation.

**Comment by guanzo** [comment]
Ooooohhhh... I need to put it on the service of MY pod. Not the service of the ingress controller. Correct?
