### ISSUE TITLE
defaultTLSSecret is only valid if it is in the Release Namespace

### ISSUE THREAD

**Issue by Mo3m3n** [haproxytech/helm-charts#67]
Currently [defaultTLSSecret](https://github.com/haproxytech/helm-charts/blob/b363778dfbd5ac41246b67e0043dbe01c5afc83b/kubernetes-ingress/values.yaml#L148) is only valid if the user provides the name of a secret in Release Namespace as we can see here https://github.com/haproxytech/helm-charts/blob/b363778dfbd5ac41246b67e0043dbe01c5afc83b/kubernetes-ingress/templates/controller-deployment.yaml#L80

While the controller can fetch the secret from any NS provided that the input is in the NS/secretName format.
This is related to https://github.com/haproxytech/kubernetes-ingress/issues/300
So I am opening this issue to report if it is possible for a user to provide a secret format 'NS/secretName'

**Comment by brianrudolf-ep** [comment]
I just hit this problem as well. 

I think that simply adding a value to specify the secret namespace, with a default value of the release namespace would provide the same functionality as the chart already does while **also** allowing this customization. 

I've opened #72
