### ISSUE TITLE
haproxy: feature request: support for configurable volumes

### ISSUE THREAD

**Issue by dpkirchner** [haproxytech/helm-charts#75]
It'd be helpful to have a way to mount volumes in the haproxy Deployment and DaemonSet objects. I saw a similar GH issue but it was specifically for the ingress chart whereas I'm using the bare haproxy chart.

This would be useful to allow us to mount secrets or configmaps into the pod, for things like TLS certificates (e.g. `server name host:port ssl crt /path/to/mounted/file.crt`).

**Comment by dkorunic** [comment]
Agreed @dpkirchner, it's already in the works and due to other projects it wasn't completed. We'll make this happen soon.

**Comment by dkorunic** [comment]
Partially implemented with PR #77 merge (secrets only for now).
