### ISSUE TITLE
Literal '{{ .Release.Namespace }}'  used when setting only 'controller.defaultTLSSecret.secret'

### ISSUE THREAD

**Issue by jobcespedes** [haproxytech/helm-charts#81]
v1.15.0

Using a custom default ssl certificate without setting controller.defaultTLSSecret.secretNamespace (default used) gives warning:
```
WARNING haproxy/certificates.go:63 namespace '{{ .Release.Namespace }}' does not exist
```
Could it be related to using `{{ .Release.Namespace }}`  in values.yaml?:
https://github.com/haproxytech/helm-charts/blob/a08c3388095da84225b61f3574a238e3938b303c/kubernetes-ingress/values.yaml#L153

**Comment by dkorunic** [comment]
Can you please confirm which Helm version are you yousing @jobcespedes?

**Comment by jobcespedes** [comment]
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

**Comment by dkorunic** [comment]
I can confirm, bug introduced by b97a0a3d changes.
