### ISSUE TITLE
Latest haproxy chart is not released

### ISSUE THREAD

**Issue by malhotraamit236** [haproxytech/helm-charts#89]
There were changes made to haproxy chart - that add extraVolume, but seems like the chart isn't released with the new version
related commit - https://github.com/haproxytech/helm-charts/commit/272db4dd5b6805a05e552d539b9d59bea42cb9ff 

as of now the latest version on haproxy chart is 1.3.0 and it doesn't have the above mentioned changes

**Comment by dkorunic** [comment]
@malhotraamit236 We generally don't make releases after *every* feature add.

**Comment by malhotraamit236** [comment]
@dkorunic thanks for releasing 1.4.0 :)
