### ISSUE TITLE
typo in port number

### ISSUE THREAD

**Issue by ganasubrgit** [haproxytech/helm-charts#96]
wrong port: 1042
   
   https://github.com/haproxytech/helm-charts/blob/1d6a9f5b2137e0c11a634c4baafc602f209c6717/kubernetes-ingress/values.yaml#L101

https://github.com/haproxytech/helm-charts/blob/1d6a9f5b2137e0c11a634c4baafc602f209c6717/kubernetes-ingress/values.yaml#L112

https://github.com/haproxytech/helm-charts/blob/1d6a9f5b2137e0c11a634c4baafc602f209c6717/kubernetes-ingress/values.yaml#L123

**Comment by dkorunic** [comment]
@ganasubrgit No it is not a typo, look at the config more closely. There is a frontend for /healtz binded to 0.0.0.0:1042:
https://github.com/haproxytech/kubernetes-ingress/blob/cbf5aeac1b6e928f2d8e61f3d66a46b15210aa7e/controller/controller.go#L248. Marking as invalid and closing.
